### ISSUE TITLE
Failed to build pip wheel for SkyPilot

### ISSUE THREAD

**Issue by jonassteinberg1** [run-house/runhouse#1041]
**Describe the bug**
Skypilot _wheels_ failed to build so `rh.cluster().up_if_not()` fails to work. A lot of skypilot is in fact built successfully, but for whatever reason the skypilot wheels are not built. I wouldn't say this is an issue per se just with skypilot, because I ran this runhouse example on my mac and it worked, so whatever the case it is impacting runhouse on Ubuntu 22.04 as well. I have collected all relevant information and attached it as logs.

**Repro**

Follow the runhouse [demo](https://www.run.house/examples/llama3-8b-chat-model-inference-aws-ec2#deploy-llama-3-8b-chat-model-inference-on-aws-ec2) on Ubuntu 22.04

SEE THE ATTACHED LOGS
[collect_env.log](https://github.com/user-attachments/files/16313689/collect_env.log)
[runhouse.1.log](https://github.com/user-attachments/files/16313691/runhouse.1.log)
[runhouse.2.log](https://github.com/user-attachments/files/16313692/runhouse.2.log)
[runhouse.log](https://github.com/user-attachments/files/16313694/runhouse.log)

**Versions**
Please run the following and paste the output below.
```
wget https://raw.githubusercontent.com/run-house/runhouse/main/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Additional context**
- python 3.11.9
- ubuntu 22.04
- nothing out of the ordinary on this box. no proxies, no weird security things. just a box on a home network with full open access to the internet. clearly none of that has anything to do with this, but box works fine in all other respects.

**Comment by dongreenberg** [comment]
Oh strange, thank you for flagging. Could you try upgrading your `setuptools` or `packaging` installations? SkyPilot rebuilds it's own wheels to install itself on the remote box, so if something is wrong with that build (e.g. a missing dependency constraint in their setup) we need to report it up to them.

**Comment by jonassteinberg1** [comment]
sure can. one minute here.

**Comment by dongreenberg** [comment]
Great! @concretevitamin for viz
