### ISSUE TITLE
[KIT-63] Replace `reqs` with `env` to run inside conda or docker env

### ISSUE THREAD

**Issue by jlewitt1** [run-house/runhouse#20]
<sub>From [SyncLinear.com](https://synclinear.com) | [KIT-63](https://linear.app/runhouse/issue/KIT-63/replace-reqs-with-env-to-run-inside-conda-or-docker-env)</sub>

**Comment by carolineechen** [comment]
Some API design and thoughts on this, along with how to simultaneously address #32 
  
`rh.Function` changes to take in an env and not a reqs
- Env contains reqs, using the same underlying package class, with minimal change
- Change to how "./" is being handled
    - Currently "./" is being added to reqs and synced over every time in order to be able to get remote_import_path for fn_ptrs.
      This "./" cwd is being fully synced, sometimes unnecessarily (and may be large/problematic in Colab type envs).
      The "./" directory can be different depending on where the user is loading/running a function from.
    - Instead, environment takes in a working_dir path (or possibly a rh.folder object), and this is rsynced onto the cluster. 
      If the user wishes to share the function or reload in a diff environment, they can store the working directory on s3/storage.
    - If a user is already specifying all other dependencies to be able to run a function, adding this working_dir param
      should be little extra effort for them.
    - How Ray handles [runtime_env](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference), using `working_dir`, `py_modules`, and `excludes`
    - Support locally changed modules, through `modules` argument, which syncs over local code to the system, and installs it. If the user wishes to share the function or reload in a diff environment, they can store the working directory on s3/storage.
    - Conda env support, takes in conda yaml files/dicts to create a conda environment, as opposed to base Python env.
    - Docker Image support, TBD need to dig more into this

```
rh.env(
    reqs: Union[str, List[str]],  # pip requirements, as a requirements.txt file or List of reqs
    conda_env: Union[str, Path, Dict],  # dict or path to yml, {'name': 'env_name', 'dependencies': ['torch=1.12.0', 'pip=23.0', 'pip': {['diffusers']}]},
    # image: str,  # docker image
    working_dir: Union[str, Path],  # path to working directory, which will be synced over to the cluster
    modules: List[str],  # list of local modules to install. these can be git packages that have been locally modified
    # setup_commands: List[str],  # should this be handled in function, or in env, or do they both need one?
):
    # Note: only one of reqs and conda_env should be set -- reqs is for python env, conda_env for conda env
    # conda_env variable can handle any pip dependencies necessary for the conda environment

   setup/install pip and conda installations and environment
   sync over working dir
   setup/install modules
```

Functions
`env.to(system)`: sets up environment on system, including installing all relevant packages and rsyncing relevant directories
`function.to(system, env)` --> `function.to(system), env.to(system)`

new functions -- should these be put in system or env class, or both?
- `system.setup_env(env)` [equivalent to env.to(system)]
- `system.activate(env)`
- `system.deactivate(env)`
- `system.delete(env)`

Questions
- drawing inspiration from [Ray runtime env](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference), should these arguments also be supported or not necessary yet -- `env_vars`, `excludes`?
- should env support `setup_cmds` (when would it be useful?), or is that duplicative with function's `setup_cmds`?
- should functions above be defined in system or env class, or both?

Things to watch out for
- conda python env consistency with packages synced over and the cluster
