### ISSUE TITLE
How is this different then Modal?

### ISSUE THREAD

**Issue by bryanhpchiang** [run-house/runhouse#262]
Curious

**Comment by dongreenberg** [comment]
Modal offers hosted compute, while Runhouse allows you to send your app to your own compute or cloud accounts. We actually plan to support Modal as a compute backend underneath Runhouse sometime soon. We're focused on different things. Modal is focused on fixing the cloud experience itself, including the DevX, while we're focused on allowing you to deploy and share backend apps anywhere. We spend most of our effort making it possible to deploy any python app to any infra, and bundle it with auth, certs, telemetry, automation, etc. such that it's production-grade and sharable out of the box. That also means that we're also a bit more aggressive about being agnostic to existing code (e.g. we don't use decorators or special call signatures), and care a lot about lineage, governance, and collaboration. Modal really shines on almost every aspect of the cloud experience - cold start times, scaling, deployment, etc. - so we're eager to integrate with it to offer the best of both of our platforms.
