### ISSUE TITLE
How to use runhouse on my local server

### ISSUE THREAD

**Issue by htang2012** [run-house/runhouse#68]
**Please provide example about how to launch runhouse on my local server**

Instead of use AWS, GCP cloud etc, I don't have any of these cloud account, but I have  GPU V100 on my local server. 
I would like to know how to setup on the server/client sides and how to interactive, I have been trying all examples from:
https://github.com/run-house/tutorials, but none of them worked.  

please give more setup instructions and guidances.

Here is what I hit when I was trying to setup on-prem cluster:

$cat rh.py 
import runhouse as rh
from diffusers import StableDiffusionPipeline

def sd_generate(prompt):
    model = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-base").to("cpu")
    return model(prompt).images[0]

gpu = rh.cluster( ips=['127.0.0.1'],
                  ssh_creds={'ssh_user': 'htang', 'ssh_private_key':'/home/htang/.ssh/id_rsa'},
                  name='rh-cluster')

sd_generate = rh.function(sd_generate).to(gpu, reqs=["./", "torch", "diffusers"])
img = sd_generate("An oil painting of Keanu Reeves eating a sandwich.")
print(type(img))
img.save("sd.png")
img.show()

$ python rh.py 
INFO | 2023-05-28 04:11:35,284 | Loaded Runhouse config from /home/ytang/.rh/config.yaml
INFO | 2023-05-28 04:11:36,858 | Running command on rh-cluster: ray start --head
INFO | 2023-05-28 04:11:37,663 | Running command on rh-cluster: mkdir -p ~/.rh; touch ~/.rh/cluster_config.yaml; echo '{"name": "~/rh-cluster", "resource_type": "cluster", "resource_subtype": "Cluster", "ips": ["127.0.0.1"], "ssh_creds": {"ssh_user": "ytang", "ssh_private_key": "/home/ytang/.ssh/id_rsa"}}' > ~/.rh/cluster_config.yaml
INFO | 2023-05-28 04:11:37,773 | Setting up Function on cluster.
INFO | 2023-05-28 04:11:38,044 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-05-28 04:11:38,105 | Authentication (publickey) successful!
INFO | 2023-05-28 04:11:38,361 | Running command on rh-cluster: ray start --head
INFO | 2023-05-28 04:11:39,023 | Running command on rh-cluster: mkdir -p ~/.rh; touch ~/.rh/cluster_config.yaml; echo '{"name": "~/rh-cluster", "resource_type": "cluster", "resource_subtype": "Cluster", "ips": ["127.0.0.1"], "ssh_creds": {"ssh_user": "ytang", "ssh_private_key": "/home/ytang/.ssh/id_rsa"}}' > ~/.rh/cluster_config.yaml
INFO | 2023-05-28 04:11:39,137 | Copying local package scripts to cluster <rh-cluster>
INFO | 2023-05-28 04:11:39,327 | Installing packages on cluster rh-cluster: ['./', 'torch', 'diffusers']
Traceback (most recent call last):
  File "/home/ytang/scripts/./rh.py", line 15, in <module>
    sd_generate = rh.function(sd_generate).to(gpu, reqs=["./", "torch", "diffusers"])
  File "/home/ytang/.local/lib/python3.10/site-packages/runhouse/rns/function.py", line 119, in to
    new_function.system.install_packages(new_function.reqs)
  File "/home/ytang/.local/lib/python3.10/site-packages/runhouse/rns/hardware/cluster.py", line 205, in install_packages
    self.client.install_packages(to_install)
  File "/home/ytang/.local/lib/python3.10/site-packages/runhouse/servers/grpc/unary_client.py", line 59, in install_packages
    server_res = self.stub.InstallPackages(message)
  File "/home/ytang/.local/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ytang/.local/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1685247106.845643418","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1685247106.845642647","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>

**Comment by dongreenberg** [comment]
You're doing it right, for some reason the server is not starting on your remote box. Can you try sshing in and running `python -m runhouse.servers.grpc_server` and let me know if you get an error?

For the record we actually just totally refactored this flow to make it simpler and more robust, we just haven't released it yet. We're testing it a bit more and will release it shortly.

**Comment by htang2012** [comment]
Thanks @dongreenberg  for the quick reponse, 
I tried 
python -m runhouse.servers.grpc_server
INFO | 2023-05-28 16:22:02,690 | Loaded Runhouse config from /home/ytang/.rh/config.yaml
/usr/bin/python: No module named runhouse.servers.grpc_server

**Comment by jlewitt1** [comment]
Hi @htang2012 can you try changing the command slightly to: `python -m runhouse.servers.grpc.unary_server`?

**Comment by htang2012** [comment]
python ./rh1.py 
INFO | 2023-05-29 00:19:14,575 | No auth token provided, so not using RNS API to save and load configs
INFO | 2023-05-29 00:19:20,463 | Running command on rh-cluster: ray start --head
INFO | 2023-05-29 00:19:27,213 | Running command on rh-cluster: mkdir -p ~/.rh; touch ~/.rh/cluster_config.yaml; echo '{"name": "~/rh-cluster", "resource_type": "cluster", "resource_subtype": "Cluster", "ips": ["127.0.0.1"], "ssh_creds": {"ssh_user": "ytang", "ssh_private_key": "/home/ytang/.ssh/id_rsa"}}' > ~/.rh/cluster_config.yaml
INFO | 2023-05-29 00:19:29,908 | Setting up Function on cluster.
INFO | 2023-05-29 00:19:30,224 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-05-29 00:19:30,285 | Authentication (publickey) failed.
INFO | 2023-05-29 00:19:30,294 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-05-29 00:19:30,383 | Authentication (publickey) successful!
2023-05-29 00:19:30,384| ERROR   | Problem setting SSH Forwarder up: Couldn't open tunnel :50052 <> 127.0.0.1:50052 might be in use or destination not reachable
ERROR | 2023-05-29 00:19:30,384 | Problem setting SSH Forwarder up: Couldn't open tunnel :50052 <> 127.0.0.1:50052 might be in use or destination not reachable
INFO | 2023-05-29 00:19:30,705 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-05-29 00:19:30,809 | Authentication (publickey) failed.
INFO | 2023-05-29 00:19:30,817 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-05-29 00:19:30,949 | Authentication (publickey) successful!
INFO | 2023-05-29 00:19:31,205 | Copying local package work to cluster <rh-cluster>

and hangs

**Comment by htang2012** [comment]
Thanks @dongreenberg, I finally got it working:
here is what I did:
on the server side:
1)  ray start --head
2)  python -m runhouse.servers.grpc.unary_server
3)  runhouse login

**Comment by dongreenberg** [comment]
Excellent! We're actually about to push a release which will address this exactly.
