### ISSUE TITLE
Consistantly hit "http.client.BadStatusLine" issue in self-hosted tests. 

### ISSUE THREAD

**Issue by htang2012** [run-house/runhouse#72]
**Describe the bug**
Hi recently I constantly hit BadStatusLine issue as follows, may be it is related to urllib library issue?

client@4c31ddeb9ade:/zip$ python test_self_hosted_llm.py
INFO | 2023-06-14 18:24:16,048 | No auth token provided, so not using RNS API to save and load configs
INFO | 2023-06-14 18:24:16,921 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-06-14 18:24:16,981 | Authentication (publickey) successful!
2023-06-14 18:24:16,982| ERROR   | Problem setting SSH Forwarder up: Couldn't open tunnel :50052 <> 127.0.0.1:50052 might be in use or destination not reachable
ERROR | 2023-06-14 18:24:16,982 | Problem setting SSH Forwarder up: Couldn't open tunnel :50052 <> 127.0.0.1:50052 might be in use or destination not reachable
INFO | 2023-06-14 18:24:17,115 | Connected (version 2.0, client OpenSSH_8.9p1)
INFO | 2023-06-14 18:24:17,174 | Authentication (publickey) successful!
INFO | 2023-06-14 18:24:17,224 | Running command on rh-cluster: pkill -f "python -m runhouse.servers.http.http_server"
Warning: Identity file /home/server/.ssh/id_rsa not accessible: Permission denied.
pkill: killing pid 255251 failed: Operation not permitted
pkill: killing pid 255253 failed: Operation not permitted
INFO | 2023-06-14 18:24:17,274 | Running command on rh-cluster: screen -dm bash -c 'python -m runhouse.servers.http.http_server |& tee -a ~/.rh/cluster_server_rh-cluster.log 2>&1'
Warning: Identity file /home/server/.ssh/id_rsa not accessible: Permission denied.
INFO | 2023-06-14 18:24:20,324 | Running command on rh-cluster: ray start --head
WARNING | 2023-06-14 18:24:21,357 | /home/client/.local/lib/python3.10/site-packages/runhouse/rns/function.py:110: UserWarning: ``reqs`` and ``setup_cmds`` arguments has been deprecated. Please use ``env`` instead.
  warnings.warn(

INFO | 2023-06-14 18:24:21,358 | Setting up Function on cluster.
INFO | 2023-06-14 18:24:21,495 | Installing packages on cluster rh-cluster: ['transformers', 'torch', 'Package: zip']
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 300, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ?ÿÿ?ÿÿ ?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 300, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x04\x00?ÿÿ\x00\x05\x00?ÿÿ\x00\x06\x00\x00 \x00þ\x03\x00\x00\x00\x01\x00\x00\x04\x08\x00\x00\x00\x00\x00\x00?\x00\x00'))
**Versions**
Please run the following and paste the output below.
```
wget https://raw.githubusercontent.com/run-house/runhouse/main/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

python collect_env.py
Python Platform: Linux-5.15.0-60-lowlatency-x86_64-with-glibc2.35
Python Version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

Relevant packages:
awscli==1.27.153
boto3==1.26.153
fsspec==2023.5.0
pyarrow==12.0.1
pycryptodome==3.12.0
rich==13.4.2
runhouse @ file:///tmp/runhouse-0.0.6-py3-none-any.whl
skypilot==0.3.1
sshfs==2023.4.1
sshtunnel==0.4.0
typer==0.9.0
wheel==0.38.4

sh: 1: sky: not found
sh: 1: sky: not found

**Additional context**
Add any other context about the problem here.

**Comment by dongreenberg** [comment]
Hi! Sorry for the delay, for some reason I missed this. What's happening is that Runhouse is attempting to connect to the box over an SSH tunnel (succeeds), but then attempts to start the HTTP server via SSH commands, which fail due to access denied. Could you try running `chmod -R 600 ~/.ssh` locally to set the right permissions for your keypair? This is a bit of an atypical error because you're connecting into the box but then seemingly not authenticating with the right permissions. 

The part about the request not completing is just Runhouse thinking the server started properly and attempting to send an HTTP request, which fails because the server isn't started. You can try confirming this by SSHing into the box and running `python -m runhouse.servers.http.http_server` to manually start the server, and then rerun your script to see if the installations go through (and let me know if either of those fail).

Either way, the error messages here are not great, so we'll fix that. We should be telling you the server failed to come up before we try sending the install HTTP request.

**Comment by dongreenberg** [comment]
Did any of the above work for you?

**Comment by htang2012** [comment]
Thanks @dongreenberg , I hits another issue after set permission on the keypairs. 

Just wondering, if I launch the following 4 steps sequentially, should the whole thing works? or do we have a new launch sequence? 

1) runhouse login
2) ray start --head
3) python -m runhouse.servers.http.http_server
4) python -m runhouse.servers.grpc.unary_server 


Thanks

**Comment by htang2012** [comment]
now it works with #2 and #3, thank you very much @dongreenberg
