### ISSUE TITLE
Discord links in `README` are invalid 

### ISSUE THREAD

**Issue by steve-marmalade** [run-house/runhouse#99]
Clicking on the [Discord link](https://discord.com/invite/RnhB6589Hs) in the README (both the [Discord badge](https://github.com/run-house/runhouse#%EF%B8%8F-runhouse-) and in the [Getting Help](https://github.com/run-house/runhouse#%EF%B8%8F-getting-help) section) goes to an "Invite Invalid" page:

![image](https://github.com/run-house/runhouse/assets/85196623/d57175a8-d51e-4076-aeee-656646e04d1c)

Is Discord still the recommended way to ask questions, or should I post them as Issues? I'm curious about this project :)

**Comment by carolineechen** [comment]
Hi @steve-marmalade, thanks for your interest! The existing Discord links do still seem to work for me, but here's another invite link you could try -- https://discord.gg/DBsUVbTS. Let me know if this works

**Comment by steve-marmalade** [comment]
Hi @carolineechen , thanks for the quick response. When clicking the URL I still get the invalid link message, but when I paste the link into the Discord "Add Server" prompt directly it worked fine. So it could be something wrong with my environment. Will close!
